### ISSUE TITLE
Redesign HTML pages using Jinja2 

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#10]
- Redesign all pages using template inheritance.

**Comment by Tititesouris** [comment]
I've made a few Flask apps before, so I'll take a look! :)

**Comment by HemendraKhatik** [comment]
You're most welcome @Tititesouris buddy!!

**Comment by Tititesouris** [comment]
I have a few questions:
login.html is the login page
signup.html is the signup page
chatroom.html is the page visible when logged in
So what are ui.html and profile.html used for?

**Comment by HemendraKhatik** [comment]
@Tititesouris ui.html and profile.html are for test purposes both pages are not part of the application you can leave as it is.

**Comment by Tititesouris** [comment]
Started by abstracting the common page structure #12 
I will take a look to see if more of the pages content can be abstracted or split into small templates, but given there are only 3 pages this might be unnecessary

**Comment by HemendraKhatik** [comment]
@Tititesouris please make sure you run the application locally and test it before making the pull request.

**Comment by Tititesouris** [comment]
I did and had no issues on my end

**Comment by HemendraKhatik** [comment]
@Tititesouris there is an internal server error after login and signup please check it again then make PR.

**Comment by Tititesouris** [comment]
I will take a look as soon I have some more time (probably Thursday), but I have only changed the html files, so I don't see how that could cause an error.
Which error exactly are you getting?

**Comment by Tititesouris** [comment]
I just re-checked, login works fine for me, which error are you getting?

**Comment by HemendraKhatik** [comment]
@Tititesouris are you able to log in and signup?

**Comment by Tititesouris** [comment]
Yes for login, haven't tried sign up because my email is already used for the account I created

**Comment by HemendraKhatik** [comment]
what is your email?

**Comment by HemendraKhatik** [comment]
try email: test@test.com to create an account

**Comment by Tititesouris** [comment]
I don't want to write the email publically, but the username is Tititesouris

**Comment by Tititesouris** [comment]
yep, created 2 accounts and signed in, no problems at all

**Comment by HemendraKhatik** [comment]
@Tititesouris let me check

**Comment by HemendraKhatik** [comment]
@Tititesouris please again make PR

**Comment by HemendraKhatik** [comment]
@Tititesouris yep it's working now there was another problem in deployment. Thank you for your contribution.
