### ISSUE TITLE
Sign up details validation.

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#15]
### Sign up details validation in the flask app.
- Email should be unique.
- The password should be strong.
- If the password is weak it should display weak password.
- If the password is medium it should display medium password.

**Comment by da201501181** [comment]
Hi, @HemendraKhatik I would like to take up this issue as a part of Hacktoberfest. Can you please tell me the criteria you would like to use for weak, medium and strong password?

**Comment by HemendraKhatik** [comment]
@da201501181 
These are the conditions.

- one upper case letter, one lower case letter, one symbol and digits, and password should be 8 letters long for a strong password.
- If any of the one condition is missed from the above conditions password would be medium.
- If any of the two or three conditions are missed from the above conditions password would be weak.

Note - you will use the flash message to display strong, weak and medium password 

feel free to ask more questions.

**Comment by da201501181** [comment]
@HemendraKhatik Taking this up.

**Comment by da201501181** [comment]
@HemendraKhatik Is the flash message to display password strength and uniqueness of email supposed to be shown dynamically or on submission of the form? 
If the password is any of the strength levels, do we need to stop the user from signing up?

**Comment by HemendraKhatik** [comment]
@da201501181 nope user can sign up we just need to show them that their password is strong or weak or medium and the flash message should be displayed on the signup form.

**Comment by da201501181** [comment]
@HemendraKhatik If the user is signing up with an email that already exists in our system, we are supposed to ask the user to login as there is an account already linked for that email. Right?

**Comment by da201501181** [comment]
The flash message should be displayed on signup form but is it supposed to be dynamic like while users are typing or after the form has submitted? I believe it should be dynamic as user types we judge the criteria and display the strength.

**Comment by HemendraKhatik** [comment]
@da201501181 it should be dynamic

**Comment by Manjeete** [comment]
@HemendraKhatik  I would like to work on this.

**Comment by HemendraKhatik** [comment]
@da201501181 are you working on this issue ??

**Comment by da201501181** [comment]
@HemendraKhatik Nope!

**Comment by siriuswapnil** [comment]
Hey @HemendraKhatik , I would like to work on this issue.

**Comment by HemendraKhatik** [comment]
@siriuswapnil sure

**Comment by HemendraKhatik** [comment]
@siriuswapnil Are you working on this issue?

**Comment by siriuswapnil** [comment]
Yes @HemendraKhatik . I might need some time. Is it urgent?

**Comment by HemendraKhatik** [comment]
@siriuswapnil nope take your time and feel free to ask for help.

**Comment by siriuswapnil** [comment]
Okay @HemendraKhatik .Give me a day.
