### ISSUE TITLE
login validation

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#16]
- If the user enters invalid details then show the flash message "Invalid password"
- If the user account does not exist then show the flash message "Account does not exist"
- Flash message should be displayed on login.html

**Comment by erikhajsakvojtko** [comment]
Hi, do you think I could work on this issue?

**Comment by HemendraKhatik** [comment]
@erikvojtko  give it a try this is the only way you can learn new things.

**Comment by erikhajsakvojtko** [comment]
@HemendraKhatik Thanks a lot, can you asign me as well?

**Comment by HemendraKhatik** [comment]
@erikvojtko there is no need for the assignment.

**Comment by da201501181** [comment]
@HemendraKhatik Taking this up!

**Comment by erikhajsakvojtko** [comment]
@da201501181 Hello, would you mind leaving it for me?

**Comment by HemendraKhatik** [comment]
@erikvojtko It's open for all

**Comment by da201501181** [comment]
@erikvojtko Ya sure, you try first.

**Comment by da201501181** [comment]
@HemendraKhatik Where should be the flash placed on the page?

**Comment by HemendraKhatik** [comment]
@da201501181 the message should be displayed on login.html or signup.html. Above username

**Comment by da201501181** [comment]
@HemendraKhatik Please review PR #24.

**Comment by erikhajsakvojtko** [comment]
@HemendraKhatik Completed in PR #25

**Comment by HemendraKhatik** [comment]
@erikvojtko this issue has been solved, please try for signup validation.
