### ISSUE TITLE
Fix time issue in Flask Application.

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#23]
- In the chatroom, message time should be displayed according to the different time zone.
- Currently, it is showing time according to the US time zone.

For more clarification feel free to ask questions.

**Comment by alidaghighi** [comment]
Maybe I can help :)

**Comment by HemendraKhatik** [comment]
@alidaghighi great

**Comment by alidaghighi** [comment]
Hey!
How can I be in touch with you? I mean could you send me your email or something that I can tell you something about this repo? :D

**Comment by HemendraKhatik** [comment]
@HemendraKhatik emmi2jerry@gmail.com

**Comment by da201501181** [comment]
#26 Please review the PR. @HemendraKhatik
