### ISSUE TITLE
Redesign UI of login.html page

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#27]

**Comment by siriuswapnil** [comment]
@HemendraKhatik what changes do you have in mind?

**Comment by HemendraKhatik** [comment]
@siriuswapnil  I Just Want New look for login.html Feel Free To Be Creative.

**Comment by TrojanTarun** [comment]
Hello Sir,
I would like to work on this issue .

**Comment by HemendraKhatik** [comment]
@TrojanTarun sure
