### ISSUE TITLE
Improvements in Backend

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#3]
### **Improvements in Backend**
You can find any bug or error and can fix it

**Comment by thebhushanmhatre** [comment]
Hi @HemendraKhatik 
I would have look into this.
Since there is no specific issue here, Others should also be able to work on this as well independently.

**Comment by orioncx** [comment]
Hi. What is the reason of having os.py and functools.py in root directory? it causes problems with imports and site doesn't work on some versions of OS and Python

**Comment by HemendraKhatik** [comment]
@orioncx  Thanks buddy it's working without those files as well. I had those files because I have to put those dependencies in requirements.txt and while deployment I was getting an import error but now it's working without those dependencies.
