### ISSUE TITLE
Create a About.html page in flask

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#30]
**Points to keep in mind**

- Make sure you are using template inheritance in jinja2
- webpage should be responsive 
- collect details to put in about.html from readme.md

feel free to ask more details and any questions.

**Comment by sandy9808** [comment]
Hello, i would love to work on this..

**Comment by astha-garhewal** [comment]
@HemendraKhatik can I also work on this issue 😬

**Comment by HemendraKhatik** [comment]
@astha-garhewal sure!
