### ISSUE TITLE
Registration Error On Live Site

### ISSUE THREAD

**Issue by Siddhant-K-code** [HemendraKhatik/FlackApp#37]
While registering on the live site it is giving, `weak password` error irrespective of that password length is16-18+

**Comment by vikrantaroraa** [comment]
Hey @Siddhant-K-code, #37 is not an error in code. You see,  the password strength is measured not only by the length of password but also with the presence of Small letters, Capital letters and Special symbols such as #, ? etc.
So,  Initially the password strength is zero. say "Abcdefgh?12" is my password:
Then,
password_strength = 1( length >=8),
password_strength = 2( Presence of Capital Letters ),
password_strength = 3( Presence of Small Letters ),
password_strength = 4( Presence of '?' )

For more info, check the function on line 130 of application.py file.
