### ISSUE TITLE
Fix responsiveness issue of application using bootstrap or custom CSS.

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#8]
* [visit the web](http://flack-web-app.herokuapp.com/) observe the responsiveness of the website and fix it.
* before making changes please make sure you read the instructions carefully in the readme file

**Comment by amelia678** [comment]
I would like to work on this!

**Comment by amelia678** [comment]
I am having trouble logging in locally, is there a step to setting up the database that's not included in the readme? (sorry I don't have any experience with flask apps)

**Comment by HemendraKhatik** [comment]
hey, @amelia678 which operating system you are currently using?

**Comment by amelia678** [comment]
@HemendraKhatik macOS high sierra

**Comment by amelia678** [comment]
@HemendraKhatik just got it working! are there any pages in particular you want to fix responsiveness to?

**Comment by HemendraKhatik** [comment]
@amelia678 login.html and signup.html

**Comment by HemendraKhatik** [comment]
@amelia678 can you enhance the chatroom.html design and responsiveness as well?

**Comment by amelia678** [comment]
yes, I'll work on it!

**Comment by siriuswapnil** [comment]
@HemendraKhatik , any more pages to work on?
